# project_id: '624128'
# api_token: '901821f0e10e2eac626679a2885e61b46c80ae4e63867c555c882fbdd27d1eea9c01d75c2fe3bd6d'
# preserve_hierarchy: true
files:
  # - source: /i18n/en/code.json
  #   translation: /i18n/%locale%/%original_file_name%
  # Docs Markdown files
  - source: /docs/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore:
      - /docs/**/*.yml
  # Blog Markdown files
  - source: /blog/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-blog/**/%original_file_name%
