name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # - name: Cache pnpm modules and build
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       node_modules
      #       build
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('**/#pnpm-lock.yaml') }}


      - name: install
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: build
        run: pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: dist-pages
          folder: build
